### ISSUE TITLE
"Use map skins" glitches a bit

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#1]
![](https://user-images.githubusercontent.com/8611110/75111840-d89ba580-5646-11ea-9057-27c2d6dcb9d1.png)

As you can see, the arrow has a weird outline and the map itself should have no outline either.

**Comment by Bulldog83** [comment]
Ок. I've removed border, but cursor looks normal.
![2020-02-23_21 34 03](https://user-images.githubusercontent.com/20737750/75117678-b4f75000-5684-11ea-8b90-45bbab9e3c4b.png)

**Comment by Bulldog83** [comment]
Does Arrow still have outline?

**Comment by Madis0** [comment]
Yes, it does.

**Comment by Bulldog83** [comment]
I've tryed to fix arrow picture and add simple arrow (red triangle). Last build on curse.

**Comment by Bulldog83** [comment]
Has anything changed?

**Comment by Madis0** [comment]
Both arrows work well.
