### ISSUE TITLE
Update to 1.17.1

### ISSUE THREAD

**Issue by KhanterWinters** [Bulldog83/JustMap#102]
How could we, users aid to update the mod into the 1.17.x ?

**Comment by bogdan-barbu** [comment]
By porting it to 1.17 and then making a pull request. There's an old 1.17 branch already, could start there.

**Comment by Bulldog83** [comment]
I haven't enought time at this moment for making 1.17 version.

**Comment by magicus** [comment]
@KhanterWinters FWIW, I've made a 1.17.1 port, available in https://github.com/magicus/JustMap/tree/1.17.1. If you know how to compile and build the mod yourself, feel free to try it out, and report any bugs to me. (Known issue right now is that grid lines do not work).

**Comment by magicus** [comment]
@Bulldog83 unfortunately does not seem very active in the project currently. :-(

I have decided to publish a binary build of my 1.17.1 version of the mod. It is available here:
https://github.com/magicus/JustMap/releases/tag/1.2.28-1.17.1-magicus-release
