### ISSUE TITLE
Opt-out cave maps and entity radar on servers

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#12]
> By default on the dedicated servers disabled Caves maps and Entities radar.
> It can be enabled via send to players a system (from the server) message with color codes:

I don't quite understand why did you make this opt-in instead of opt-out. 

Some arguments:

- even if the features are allowed per server rules, this mod is currently small enough that many admins wouldn't bother to allow it
- per previous argument, admins may not know _how_ to properly enable this or _may not be able to_ (specific plugins overriding something, etc.)
- the enforcement of the rules is still up to server admins regardless of this setting, in other words the user may just use a hack mod or such to enable a similar feature

**Comment by Bulldog83** [comment]
When I started working on the map, I primarily focused on one popular Russian server of minecraft. On this server, rules prohibit the display of caves and entities on the map. Therefore by default I did it to hide. And I don't want to change this setting. Most servers use a welcome message when you log on to the server, it's not difficult to add to the end of that message the combination of color codes.
