### ISSUE TITLE
config file is not created on server

### ISSUE THREAD

**Issue by agaertner** [Bulldog83/JustMap#13]
Hey, so the config file is not created when I run it on my server and there is no way to access the settings of the server via in-game
I need to edit the config file but it is not there. It seems the server boots up the mod and runs default settings every time.

It is completely useless without seeing at least players.

shouldn't it be here? 
``<root>/config/*.json``

**Comment by Bulldog83** [comment]
This mod is for the client only. The server simply doesn't know about it. Therefore, the config is not created.
Hm. I try to create gamerules for server side, wich it will be possible to activate radar and cave mapping. Or you can send to the players special message from the server, to activate it. But, it need to do every time.

**Comment by agaertner** [comment]
I need a minimap that force disables the entity view on servers.
Only players.

**Comment by Bulldog83** [comment]
Yes, it possible.

**Comment by Bulldog83** [comment]
Done via 5ca1a63af848c232d6947e68495d83fa70182cb1. Soon it will appear on Curse.

**Comment by agaertner** [comment]
Sorry, so this means it will be enforceable when it is installed on the server?

**Comment by Bulldog83** [comment]
If you'll install mod on the server you'll can controll radar and cave mapping via game rules or mod config. To enable players radar only you need to enable entity and player radars and to disable creatures and hostile radars.
