### ISSUE TITLE
Crash with CraftPresence

### ISSUE THREAD

**Issue by furtabs** [Bulldog83/JustMap#14]
https://pastebin.com/fAgm1H25

**Comment by Bulldog83** [comment]
Hm. Looks like CraftPresence calls my class too early..

**Comment by Bulldog83** [comment]
Yes. CraftPresence looks for Screen based classes and because of this by chain calls my classes which should be called much later. Ok. I'll think how to change init for these classes.

**Comment by Bulldog83** [comment]
Fixed ff7d6d1bbe04e1716376e2f1ce39d35b679744ca
