### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#15]
Sometimes entity icons become hidden during movement and sometimes the whole map appears in front of the cardinal points/arrow/entity icons.

Unfortunately I haven't found a consistent way to reproduce it, nor did I capture it on video.

**Comment by Bulldog83** [comment]
Hmm. Icons can hides if difference of height pos between you and mobs too big. But whole map.. Technically, this shouldn't be.

**Comment by Bulldog83** [comment]
Does problem still exists?

**Comment by Madis0** [comment]
Cannot reproduce at the moment.
