### ISSUE TITLE
Waypoint Icon issue

### ISSUE THREAD

**Issue by ghost** [Bulldog83/JustMap#16]
The waypoint breaks out of the maps outline; see image
![2020-03-10_20 28 05](https://user-images.githubusercontent.com/13181379/76351517-df483f00-630d-11ea-95e0-116003bfb435.png)
[latest.log](https://github.com/Bulldog83/JustMap/files/4314375/latest.log)

**Comment by Bulldog83** [comment]
Yes, I've known it already. It will be fixed soon.

**Comment by Bulldog83** [comment]
Fixed in last version
