### ISSUE TITLE
Game performance tanks with mod installed

### ISSUE THREAD

**Issue by whatanoob** [Bulldog83/JustMap#18]
I've tried running the game with just this mod, the Fabric API and Mod menu on, but I was still getting around 18 fps. Disabling entity tracking also did nothing for me. With the mod disabled I get around 200 fps.

Here's a recording with the mod enabled, and the respective log file:
https://streamable.com/hyj1k
[2020-03-12-6.log.gz](https://github.com/Bulldog83/JustMap/files/4323843/2020-03-12-6.log.gz)

And this is how my game performs with the mod disabled:
https://streamable.com/rz3rw

I've also tried running the 1.15.2 and 20w09a versions but the issue persists.

**Comment by Bulldog83** [comment]
Do you play on Linux?

**Comment by whatanoob** [comment]
No, I play on Windows 10.

**Comment by Bulldog83** [comment]
Fixed?

**Comment by whatanoob** [comment]
Just tested the 20w14a version and it's working great. Good job!

**Comment by whatanoob** [comment]
Just tested the 20w14a version and it's working great. Thanks!
