### ISSUE TITLE
Current skin picker should be more user-friendly

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#2]
Since you have a lot of skins, using the slider makes the selection difficult, especially because the name updates only after saving the settings.

So here are some ways this could be improved:

- A dropdown or list of skins
- Semi-transparent settings with an apply button
- Image previews, of an actual map or just the outlines (maybe like you did with the waypoint icons?)

**Comment by Bulldog83** [comment]
I tried to make a dropdown menu for skins. But the widget from ClothConfig doesn't display the list. I want to create issue on it's github.

**Comment by shedaniel** [comment]
We can work this out together.

**Comment by Bulldog83** [comment]
Of course, here's issue on your GitHub: https://github.com/shedaniel/ClothConfig/issues/27

**Comment by Bulldog83** [comment]
Drop down menu fixed via 0b0c552cc7914e3ce9085dad22ae3ea823f8319c. Just delete current skin name and you will see anothers.
