### ISSUE TITLE
About Chinese translate file

### ISSUE THREAD

**Issue by nicklly** [Bulldog83/JustMap#21]
Hello!
I am tonyair2019, I leave a message to you on curesforge, hoping to publish a language document with Chinese,And when you later develop mod, I can continue to issue this file to you by submitting it to GitHub or I will issue it separately and get your consent.

In addition, I found the en_us in the Lang folder, and the JSON is missing the text configuration of key.justmap.show_worldmap.

I've uploaded the screenshot and two copies of Lang are in justmap-lang.zip

![QQ截图20200321204343](https://user-images.githubusercontent.com/17716585/77226841-4ee3e700-6bb6-11ea-8f6c-42e41c370f03.png)

[JustMap-lang.zip](https://github.com/Bulldog83/JustMap/files/4362876/JustMap-lang.zip)

**Comment by Bulldog83** [comment]
Ok, thanks! Merged.
