### ISSUE TITLE
Crash when above Y level 256

### ISSUE THREAD

**Issue by HiJack-47** [Bulldog83/JustMap#22]
When playing with this mod installed I flew to above y level 256 using an Elytra and trident in the rain and got a game crash as well as crashes as soon as i loaded back in with an array index error. Took mods out of my folder until i removed Just Map and crash no longer occurred, returned to below y level 256 and the mod was able to be re-added without crashing. I tested it again and every time i go above 256 my game crashes with the same error

**Comment by Bulldog83** [comment]
Fixed
