### ISSUE TITLE
Accidentally creating waypoints when hitting buttons in map view

### ISSUE THREAD

**Issue by crabdancing** [Bulldog83/JustMap#24]
As of 1.0.4, when I click one of the buttons twice quickly in the map view (after pressing M), I see a waypoint dialog pop up. This to me seems like a bug. I would suggest having the 'prompt to create waypoint' function not run if the cursor is within the boundaries of any of the buttons.

**Comment by Bulldog83** [comment]
Very strange. I have already fixed this, but for some reason the changes were not saved...

**Comment by Bulldog83** [comment]
Fixed
