### ISSUE TITLE
Fullscreen Map Panning

### ISSUE THREAD

**Issue by HiJack-47** [Bulldog83/JustMap#26]
It appears as though the speed of panning on the full screen map doesn't scale with the amount that the map is zoomed in. Pan speed should scale to make it easier to move larger distances on the map when zoomed out

**Comment by Bulldog83** [comment]
Does it better now?

**Comment by HiJack-47** [comment]
It doesn't appear to pan any faster when zoomed out. It also now only moves the map when you release the mouse as opposed to following it when zoomed all the way out

**Comment by Bulldog83** [comment]
There is a problem here.  With a large scale map dragging begins to lag.  Therefore, I limited the number of the map updates per second.  Prior to that, it depended on the scale: the larger the scale, the fewer updates.  Now I tried to make a fixed delay.  Apparently, it’s more optimal, after all, to return to dependence on the scale of the map.

**Comment by HiJack-47** [comment]
I assumed it might be a problem with the fact that it has a lot of pixels/map elements to move all at once. The only thing i might suggest is finding a way of reducing the resolution as you zoom out to allow this to be less laggy, otherwise if there's no easy way to do it don't worry about it.

**Comment by HiJack-47** [comment]
As of 1.0.48 Map panning only refreshes when you make an adjustment to the zoom level
