### ISSUE TITLE
Map updates

### ISSUE THREAD

**Issue by HiJack-47** [Bulldog83/JustMap#29]
Map only updates when placing blocks and doesn't update when blocks are removed

**Comment by HiJack-47** [comment]
whoops pressed enter before i'd typed anything, Map only updates when placing blocks and doesn't update when those blocks are removed

**Comment by HiJack-47** [comment]
Note: Closing down the world and reloading updates the map correctly

**Comment by HiJack-47** [comment]
This still appears to be an issue

https://imgur.com/a/f69t8Hd

Notice the patches of water shown on the map that aren't there in the world,
Reloading the world hasn't fixed this nor has reloading the game

Unless this fix isn't in 1.0.46 in which case ignore me

**Comment by Bulldog83** [comment]
Issue was closed automatically. I haven't uploaded the update to the Curse yet. I'll do it tomorrow.
