### ISSUE TITLE
Entity display improvements

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#3]
Some things I noted:

- Default entity model size should be 5, otherwise it is just too big
- The squids appear a lot larger than other models; while I am using a resource pack it seems like a problem with this mod
- As you can see on the VoxelMap, the entity heads are better highlighted if they have an outline, please add an option for that.

JustMap vs VoxelMap:
![asdas](https://user-images.githubusercontent.com/8611110/75111972-1d740c00-5648-11ea-8dc6-0106656d7346.png)

**Comment by Bulldog83** [comment]
The outline for icons add via 0b0c552cc7914e3ce9085dad22ae3ea823f8319c, but disabled by default.

**Comment by Bulldog83** [comment]
Done dd36ae3d09777a4758195d930baae54ec826b27b
