### ISSUE TITLE
Map wouldn't render until I placed a dirt block above a beehive and restarted my game

### ISSUE THREAD

**Issue by jwwilliams1994** [Bulldog83/JustMap#31]
As title says, map was just a black box, but in the overworld it had tried to render a tiny part before stopping. I went to that part of the map, and I saw a beehive nearby. After covering it on top with a dirt block, and restarting my game, the map worked correctly.

The beehive was at honey_level:5, for what it's worth, and beehives pick up a new texture when full, maybe that's relevant?

**Comment by Bulldog83** [comment]
I need to see logs to say something. May be it some error in the updating thread.

**Comment by jwwilliams1994** [comment]
I actually don't know if it was specifically the hive now, it just seems to happen rarely while I'm playing on my friend's 20w13b server; if it happens again I'll try to grab the log for it, but what it does is just keep rendering as normal but rarely and randomly it'll stop drawing new/unknown blocks to the map

it's happened to my friend also, so it's not _just_ me, and thus far it's happened in both overworld and nether
I've switched to the version you released today, so if it never happens again, maybe you fixed it
