### ISSUE TITLE
Modifying potion effects causes Giselbaer's Durability Viewer to disappear

### ISSUE THREAD

**Issue by Leo40Git** [Bulldog83/JustMap#34]
Giselbaer's Durability Viewer [`@Inject`s into `InGameHud.renderStatusEffectOverlay`](https://github.com/gbl/DurabilityViewer/blob/fabric_1_14_pre2/src/main/java/de/guntram/mcmod/durabilityviewer/mixin/PotionEffectsMixin.java#L15), which is [cancelled by this mod](https://github.com/gbl/DurabilityViewer/blob/fabric_1_14_pre2/src/main/java/de/guntram/mcmod/durabilityviewer/mixin/PotionEffectsMixin.java#L15).

**Comment by Bulldog83** [comment]
If I'll remove ci.cancel() it'll duplicate status effects icons rendering. May be, it will be better to inject the item durability hud into "render" method?
