### ISSUE TITLE
Not working on Server

### ISSUE THREAD

**Issue by bookerthegeek** [Bulldog83/JustMap#35]
## Heyo! ##

So just tried your map, so good so far. Works in single player, everything good. Jump onto a server and BAM, the map is black. Not even rendering entities. I get the border, and myself. Nothing else.

### Versions
MineCraft 1.15.2
JustMap 1.0.50

**Comment by Bulldog83** [comment]
Entities, players radar and cave mapping are disabled by default on the servers and can be enabled only via special command from the server. And I checked mapping on the server, it works normal. Try the latest version of map.

**Comment by bookerthegeek** [comment]
That is understandable, this is also normal surface mapping though.
