### ISSUE TITLE
Waypoints in the end dimension permanently disappear

### ISSUE THREAD

**Issue by OpenSauce04** [Bulldog83/JustMap#36]
They still appear in the waypoint menu but are entirely gone from the map, world, and screen edge.
This either happens when leaving and re-entering the end or after logging out; Not sure which (only just noticed it on my survival world when looking for my end city waypoint)

**Comment by Bulldog83** [comment]
I've created waypoint in The End, several times reloged and reentered to The End. Waypoint don't gone. 
![2020-05-05_21 07 26](https://user-images.githubusercontent.com/20737750/81101360-afd13f80-8f16-11ea-84fc-0659d5df55d7.png)

**Comment by Bulldog83** [comment]
Try to increase waypoints render distance in the map config.
