### ISSUE TITLE
[1.15.2] Server waypoints not saving after closing MC.

### ISSUE THREAD

**Issue by shadow306k** [Bulldog83/JustMap#38]
As titled, playing on a vanilla server with friends, and using this and a couple other client-side mods
(AppleSkin, I am Very Smart, REI (JEI Clone), Mouse Wheelie), and after making some generic waypoints to things around our world, I noticed they weren't anywhere to be found today after loading up and logging in. Not in the menu or rendered in-world.

**Comment by shadow306k** [comment]
Oh, looking through the logs it seems that certain non alpha-numeric characters, in this case "!?" was causing the issue, the logs said something about an illegal character in the file path.

**Comment by Bulldog83** [comment]
Can you attach the log?

**Comment by shadow306k** [comment]
https://pastebin.com/SKShNkQP Here it is, this is the log from launching the game, (changing the server name in my multiplayer menu), joining the server, setting a waypoint and closing the game

Furthermore, this was preventing the map from rendering completely. not just waypoint bugs. No entities, no cave view, no overworld map rendering, just a black square

**Comment by Bulldog83** [comment]
Yes, it don't like the '?' character. Ok, thanks.
