### ISSUE TITLE
Hotkey for settings

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#4]
Since the user likely wants to test the settings as they apply them, an optional hotkey for the mod settings would be nice. 

Alternatively (or complementarily), why not make the settings semi-transparent? See also #2

**Comment by Bulldog83** [comment]
At the moment, most of the settings are implemented through the Mod Menu with ClothConfig. And how in this case to implement a preview of the changes I have no ideas. Perhaps in the future, I will make some settings menu directly in the game. But this, so far, is not a priority.

**Comment by Madis0** [comment]
Maybe the source of Roughly Enough Items could help? As it also uses ClothConfig and has a settings button in-game (in the inventory, on REI overlay).

**Comment by Bulldog83** [comment]
Ok, I'll look.

**Comment by Bulldog83** [comment]
Added config button to the Worldmap screen. About transparency and preview of changes, not shure, but I'll think.
