### ISSUE TITLE
[20W21A] Odd client hang adding Justmap

### ISSUE THREAD

**Issue by kwpugh** [Bulldog83/JustMap#42]
Using 1.1.62 and 20W21A

Adding Justmap to client seems to directly or indirectly cause the client to hang on start up.

log:  https://gist.github.com/kwpugh/d7ca9bcad9b85fcc9aa90f5a136ba3a1

Returns to normal when removed.

**Comment by Bulldog83** [comment]
Do you have same problem with another map mods? As I know, MacOS have problems with some Java classes.

**Comment by kwpugh** [comment]
Voxel works fine, other than being ugly.  I like your mod better.   Previous version of JustMap worked fine on the snapshots.

**Comment by Bulldog83** [comment]
Try this jar. If it'll help, I'll upload it on the Curse.
[justmap-1.1.63-20w21a.zip](https://github.com/Bulldog83/JustMap/files/4672390/justmap-1.1.63-20w21a.zip)

**Comment by kwpugh** [comment]
Works beautifully, thank you.
