### ISSUE TITLE
Server can't save gamerule

### ISSUE THREAD

**Issue by DanShu15** [Bulldog83/JustMap#43]
I'm having an issue on 1.15.2 with enabling the cave and entity maps on a server.
The server and player configs are true on both, and I can change the gamerule to true with commands just fine - but after I restart the server the gamerules reset themselves to disabled

**Comment by Bulldog83** [comment]
It's strange. Game rules must saves to the 'level.dat' of world's save folder.

**Comment by DanShu15** [comment]
yea, my pack must be missing something. Thanks anyway tho!
