### ISSUE TITLE
Constant freezing

### ISSUE THREAD

**Issue by Significante** [Bulldog83/JustMap#44]
It's freezing while I am walking. I don't do anything specifically I just walk around the map and it freezes for like 1-2 seconds. I am playing on 1.16 pre2 (using that version of the map as well) and I am also playing on a Fabric server that I am hosting.

**Comment by Significante** [comment]
Do you possibly need logs to help you fix it?

**Comment by Bulldog83** [comment]
No, I approximately know, what is the problem. I'll try to fix it with update to the pre3.

**Comment by Bulldog83** [comment]
Does problem still exists?
