### ISSUE TITLE
[Feature Request/bug?] Key used to show Worldmap should also hide the Worldmap

### ISSUE THREAD

**Issue by calloatti** [Bulldog83/JustMap#48]
MC 1.15.2
justmap-1.0.72-1.15.2-release

When I press the key to show the Worldmap, I expect the same key to hide the Worldmap when the Worldmap is visible. Currently I have to press "ESC" or click the "X" in the top right corner.

Don't know if this is a bug or a missing feature.

**Comment by Bulldog83** [comment]
Hmm. Actually, it does. I've checked it just now.

**Comment by calloatti** [comment]
Strange, it does not work for me, will test again with the default key and check for mod interactions.
