### ISSUE TITLE
[Feature Request] Add a hotkey to toggle between normal map size and an alternative (bigger) map size

### ISSUE THREAD

**Issue by calloatti** [Bulldog83/JustMap#49]
Sometimes it's nice to have a larger map for a few seconds, with the world map being overkill (besides not being able to move around)

Having a hotkey to switch between two set map sizes would be great, for example:

Normal:
![2020-06-12_02 33 52](https://user-images.githubusercontent.com/12817862/84468529-739ba800-ac55-11ea-8131-5608b8487ab7.png)

Alternative:
![2020-06-12_02 34 33](https://user-images.githubusercontent.com/12817862/84468544-7a2a1f80-ac55-11ea-8c2c-8875ff5a2697.png)

**Comment by Bulldog83** [comment]
Done for 1.15.2
