### ISSUE TITLE
crash on launch [1.16-pre 6] (java.lang.NoSuchMethodError: net.minecraft.class_2874.method_28542()Z)

### ISSUE THREAD

**Issue by SDUBZ** [Bulldog83/JustMap#51]
justmap: justmap-1.1.74-1.16-pre2

[latest.log](https://github.com/Bulldog83/JustMap/files/4787018/latest.log)
[crash-2020-06-17_00.04.17-client.txt](https://github.com/Bulldog83/JustMap/files/4787020/crash-2020-06-17_00.04.17-client.txt)

**Comment by Bulldog83** [comment]
I know about that. Map will be updated to the actual version soon.

**Comment by Bulldog83** [comment]
Map updated to 1.16-pre7
