### ISSUE TITLE
Map Skin offset messed up

### ISSUE THREAD

**Issue by ghost** [Bulldog83/JustMap#53]
As seen below, the skin for the map is too stretched. I've tried others and the borders are just as oversized. I've also tried not using the skin, but then the map just floats in the place where it is now. Changing the offset doesn't appear to do anything.
Is there a control I'm missing, or is this a bug?
EDIT: I should probably mention it's version 1.0.75, MC 1.15.2 and I just updated all the Fabric stuff. I'll list versions if you want.
<img width="2048" alt="Screen Shot cropped" src="https://user-images.githubusercontent.com/15851438/85076660-1604df80-b1b0-11ea-8f77-bedd94999007.png">

**Comment by Bulldog83** [comment]
Fixed
