### ISSUE TITLE
Map confused by void

### ISSUE THREAD

**Issue by Boobies** [Bulldog83/JustMap#59]
Try the following:

Load a map, then generate a world using the void preset for superflat worlds so there's void around. Wherever there's void, the map will show the contents of the previous world. I haven't tested further but my guess is that it simply doesn't know what to do when there are no blocks at all, meaning breaking bedrock for a void perimeter will render nonsense.

**Comment by Bulldog83** [comment]
As it appears, your Void world has a same name as the previous world. And map has loaded data for it. Because I tested it just now, and map normally works in the Void.
