### ISSUE TITLE
Localization via Crowdin

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#6]
Would be great if this mod could be translated to various languages, even better if [done via Crowdin](https://crowdin.com/page/open-source-project-setup-request) (instead of Github).

Edit: noticed that there is a language file already, but Crowdin point still stands.

**Comment by comradekingu** [comment]
@Madis0 Because Minecraft uses it? There are better alternatives IMO in terms of being libre, no spying, better functionality etc.. https://hosted.weblate.org/projects/minetest/ is on Hosted Weblate :)

**Comment by Bulldog83** [comment]
Hmm. Crowdin is free only for projects older then 2 month. Weblate is free only for selfhosted weblate servers.

**Comment by comradekingu** [comment]
@Bulldog83 
Hosted Weblate is also gratis for libre software. Look at https://weblate.org/hosting/

The Crowdin equivalent is not gratis, you have to contribute to their translation memory when you have a "free" account, as per their terms. And their pricing info says:

> Crowdin for Open Source
> 
> We support the open source community. If you're building awesome **non-profit** projects that could use the power of Crowdin, we're happy to help. Make your content multilingual to reach a global audience.
> 
> Apply for a free open source license

So not only does Crowdin lend itself to a license to the work libre software translators do, it requires the project to have no source of income too…
To make matters worse, it also helps itself to tracking users and monetizing them with targeted advertisement and other egregious policies https://support.crowdin.com/cookies/

I'll translate JustMap to nb_NO, clean up the source strings if that needs doing if it gets onto Weblate or a platform that can compare itself to it.

**Comment by Madis0** [comment]
[How about Transifex?](https://docs.transifex.com/projects/open-source-project)

**Comment by comradekingu** [comment]
@Madis0 Almost made me hide from my screen.

> Transifex offers an Open Source Program to Open Source projects that have no funding, revenue, and/or commercialization model.

Same scam, different hands in the cookie jar. If it wasn't down right now, I could link you to their terms of service.

https://hosted.weblate.org/legal/ is a whole different way of doing things.

**Comment by Bulldog83** [comment]
Crowdin mod page: https://crowdin.com/project/justmap

**Comment by Madis0** [comment]
Thanks. Please add Estonian there.

**Comment by Bulldog83** [comment]
Done
