### ISSUE TITLE
[Feature Request] Hot Key to turn all waypoints on/off

### ISSUE THREAD

**Issue by craftycorvid** [Bulldog83/JustMap#60]
It'd be great to have the ability to press a key and toggle the in-world rendering of all waypoints

**Comment by Bulldog83** [comment]
I can make a key to show/hide all waypoints, on the map, screen edge and in the world. Same as show/hide entities. I already use a lot of keys for the map. It will be overmuch, to make more keys for different displaying of waypoints.

**Comment by Bulldog83** [comment]
Done

**Comment by craftycorvid** [comment]
That was incredibly fast! Thank you!
