### ISSUE TITLE
Map position does not update when resizing game window

### ISSUE THREAD

**Issue by calloatti** [Bulldog83/JustMap#62]
justmap-1.1.84-1.16.1-unlimited.jar
MC 1.16.1
Windows 10

Start game with default non-maximized window size in MultiMC

![2020-06-30_10 37 13](https://user-images.githubusercontent.com/12817862/86132972-0f367080-babe-11ea-8580-85dd5b15493c.png)

Press [ESC]
Click on Maximize button to maximize the game window
Press [ESC] again to return to game

![2020-06-30_10 38 01](https://user-images.githubusercontent.com/12817862/86133147-4ad13a80-babe-11ea-9eee-20535cbf3f4a.png)

Pressing the "Switch to Big Map" key updates the map position.

**Comment by Bulldog83** [comment]
Download the latest mod version.
https://www.curseforge.com/minecraft/mc-mods/just-map/files
