### ISSUE TITLE
Client's map doesn't fill in when connected to server [bug]

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Bulldog83/JustMap#65]
I have a server I play on with a friend. The server runs on my PC, the same one I run my client on, and my map works properly. My friend's map, however, is perpetually just black emptiness. He can use waypoints fine, and the map works for him in his singleplayer worlds. 
We're using
minecraft 1.16.1,
justmap-1.1.89-1.16.1-release

**Comment by Bulldog83** [comment]
The server runs as separate app or you share your world on lan?

**Comment by supersaiyansubtlety** [comment]
It's a separate, dedicated server.

**Comment by Bulldog83** [comment]
Hmm. Can you attach your friend's `latest.log` file? And try latest map version (1.1.91).

**Comment by supersaiyansubtlety** [comment]
Next time he can get online we'll update, I'll start up the server for just a minute, let him run around with his map enabled, and then have him send me the log.

**Comment by supersaiyansubtlety** [comment]
Well we updated to the latest stable release and my friend's map filled in this time, so guess it got fixed in one of the updates or was some one-of issue.
