### ISSUE TITLE
Minimap does not rescale

### ISSUE THREAD

**Issue by Boobies** [Bulldog83/JustMap#66]
This is particularly annoying when you switch to/from fullscreen mode. The other game elements do change but the minimap remains the same.

**Comment by Bulldog83** [comment]
What mod version do you use?

**Comment by Boobies** [comment]
Latest build on CurseForge (1.1.91), the unlimited version.

**Comment by Bulldog83** [comment]
Hmm. Can you make some screenshots? I just tested it, and all works correctly.

**Comment by Boobies** [comment]
I don't think that is necessary because I've found a way to reproduce it. If the window size is large enough, the minimap gets scaled. Try reducing its size and you will notice the problem. The map is also not in proportion when using a low resolution in fullscreen mode. Let me know if you still can't reproduce it and I will post screenshots.

**Comment by Bulldog83** [comment]
Oh, you mean that the map doesn't automatically adjust to the size of the window? Yes, the size of the map remains the same, regardless of the size of the window. I'll think what I can do about it.

**Comment by Boobies** [comment]
Did you test it? Seems to still be the case.

**Comment by Bulldog83** [comment]
It works if Gui Scale is `Auto`. In other cases, interface scaling not depends on window size.
