### ISSUE TITLE
[Feature Request] Multiworld support

### ISSUE THREAD

**Issue by redstoneguy12** [Bulldog83/JustMap#69]
I would love to switch to this, but it has one major issue that makes it so I literally can't use it. A lot of servers use multiworld, where there are multiple worlds in the same dimension that it switches between, effectively enabling server-side dimensions. Is there any chance of this mod getting support for multiworld?

**Comment by Bulldog83** [comment]
Can you give a link to a server with such a world? I need to understand how the map works in these conditions.

**Comment by redstoneguy12** [comment]
I believe that's how minigames servers work, so you should be able to go on hypixel and see the map get messed up when you switch to a game. I'd test it and make sure, but I'm not near a computer and won't be until Tuesday

**Comment by Bulldog83** [comment]
Done. At least it works on the Hypixel server.
