### ISSUE TITLE
Waypoint display naming is confusing

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#7]
Instead of

- Hidden
- Tracking
- Render

I would suggest "Show on:"

- Minimap
- Screen edges
- World

and the "hidden" would work the opposite in this case.

**Comment by Bulldog83** [comment]
'Hidden' are fully hide a waypoint. A waypoint doesn't show anywhere.

**Comment by Madis0** [comment]
In my experience, the waypoint still appeared as set in the other options.

**Comment by Bulldog83** [comment]
Hm. It's a bug too.

**Comment by Bulldog83** [comment]
No, if set waypoint to 'hidden' it's hides both from map, traking and from the world.

**Comment by Bulldog83** [comment]
'Hidden' will stay 'Hidden'. 'Tracking' and 'Render' changed to 'Screen Edge' and 'In World'.
