### ISSUE TITLE
Manually introducing negative waypoint coordinates

### ISSUE THREAD

**Issue by Boobies** [Bulldog83/JustMap#73]
Cannot type the minus sign in the boxes, only digits are accepted. It should be possible for the first character to be a minus sign as long as it's followed by digits.

**Comment by Bulldog83** [comment]
It's normal. These fields acceps only integer values or nothing.

**Comment by Boobies** [comment]
Well negative values are integers too but you can't input them... That means you can never set a waypoint with negative coordinates without actually going there. Those inputs thus only allow you to set inputs for a quarter of the Minecraft world and the rest is inaccessible.

**Comment by Bulldog83** [comment]
You can. Just enter any digit and type minus before it.

**Comment by Boobies** [comment]
Ok but it's pretty ridiculous and no one expects software to work like that. It's so ridiculous that as a user I had to open a bug report to find out the workaround. :-/ At the very least put up some text so people know how to do it.

**Comment by Bulldog83** [comment]
It's protection from enter wrong data to the field. And you are the first to whom it caused inconvenience.
