### ISSUE TITLE
Map and minimap remain dark sometimes

### ISSUE THREAD

**Issue by calloatti** [Bulldog83/JustMap#75]
justmap-1.1.97-1.16.1-unlimited.jar

https://paste.ee/p/x40gT

![](https://user-images.githubusercontent.com/12817862/89092984-bee85200-d38c-11ea-88aa-2e90bf817828.png)

**Comment by calloatti** [comment]
Maybe the fact that the map was named TEST3/ECOTONES and MC named the world folder TEST3\_ECOTONES could be the cause of the bug?

Because I tried restarting and the problem persisted, then I renamed the folder to TEST3 and changed the map description to TEST3 and the map worked.

**Comment by Bulldog83** [comment]
Try the latest map version (1.1.98).

**Comment by calloatti** [comment]
Seems to work fine in justmap-1.1.98-1.16.1-unlimited.jar (Do you fix bugs even before people report them?) Thanks. Will report back if I notice it happening again.
