### ISSUE TITLE
Minimap and large map glitching out and updating a lot

### ISSUE THREAD

**Issue by TrashCaster** [Bulldog83/JustMap#78]
![2020-08-11_19 40 40](https://user-images.githubusercontent.com/14267662/89969363-0aabbe80-dc0b-11ea-8791-07a01c17669f.png)

This happens in the Nether above bedrock on my server. I haven't seen this happen in the overworld.
Using the new 1.16.2 version of Unlimited.

Here is my config:

`{
  "waypoints_world_render": "true",
  "advanced_info": "true",
  "show_offhand": "true",
  "show_waypoints": "true",
  "map_offset": "16",
  "skin_scale": "2.0",
  "map_visible": "false",
  "show_in_chat": "true",
  "items_position": "MIDDLE_LEFT",
  "show_chest": "true",
  "current_skin": "0",
  "big_map_size": "256",
  "purge_amount": "1500",
  "show_slime": "true",
  "map_info": "true",
  "terrain_strength": "2",
  "max_render_dist": "1000",
  "show_player_heads": "true",
  "info_position": "MIDDLE_RIGHT",
  "alternate_color_render": "true",
  "arrow_size": "6",
  "chunk_level_update_interval": "3000",
  "entity_icon_size": "2",
  "rotate_map": "false",
  "force_map_update": "false",
  "show_legs": "true",
  "simple_direction_arrow": "false",
  "draw_chunk_grid": "true",
  "show_entities": "true",
  "map_size": "96",
  "worldmap_icon_size": "8",
  "show_feet": "true",
  "use_skins": "true",
  "purge_delay": "60",
  "render_animation": "true",
  "show_time": "false",
  "show_entity_heads": "true",
  "show_icons_outline": "false",
  "map_position": "TOP_RIGHT",
  "show_topography": "false",
  "water_tint": "true",
  "chunk_update_interval": "1000",
  "hide_plants": "true",
  "show_big_map": "false",
  "render_light_beam": "true",
  "min_render_dist": "1",
  "show_hostile": "true",
  "hide_water": "false",
  "show_FPS": "true",
  "arrow_type": "PLAYER_HEAD",
  "map_brightness": "0",
  "waypoints_tracking": "true",
  "show_loaded_chunks": "false",
  "show_position": "true",
  "entity_outline_size": "1",
  "show_light": "true",
  "show_terrain": "true",
  "map_scale": "2.0",
  "show_head": "true",
  "show_mainhand": "true",
  "texture_filter": "false",
  "show_player_names": "true",
  "render_entity_model": "false",
  "show_players": "true",
  "entity_model_size": "2",
  "move_effects": "true",
  "show_items": "false",
  "show_caves": "false",
  "show_creatures": "true",
  "map_saturation": "0",
  "render_markers": "true",
  "show_biome": "true",
  "show_effect_timers": "true"
}`

**Comment by Bulldog83** [comment]
And what have you all forgotten over the ceiling ...

**Comment by TrashCaster** [comment]
> And what have you all forgotten over the ceiling ...

This didn't happen in the 1.16.1 version though.
As to why it would suddenly stop functioning correctly in the next version, I don't know.
