### ISSUE TITLE
Full screen map

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#8]
Please add a full screen map, that

- is zoomable with a mouse or +/-
- is pannable with a mouse, WASD (using same keybinds as set for player navigation) or arrow keys It should be pannable within at least within the currently rendered chunks, though you can add a recording function too if preferred)
- right click can:
  - add/modify waypoints
  - highlight any area as a temporary waypoint
  - copy coordinates of any area
- can view yourself and other entities

Inspired by VoxelMap and JourneyMap.

**Comment by Bulldog83** [comment]
Worldmap added, it shows you and waypoints. Another functionality will be later.

**Comment by Bulldog83** [comment]
Added current coordinates under cursor and creating waypoints by double-click. On this, for now, close.
