### ISSUE TITLE
Consider lighting

### ISSUE THREAD

**Issue by Madis0** [Bulldog83/JustMap#9]
Would give a better perspective on the current time of the day and heights.

**Comment by Bulldog83** [comment]
Not sure whether to display day or night on the map. At the expense of heights didn't quite understand.. You mean heights map like in JorneyMap?

**Comment by Madis0** [comment]
Can't remember how it worked in JourneyMap but in VoxelMap when you go higher than the ground, the map dims a bit.

**Comment by Bulldog83** [comment]
I don’t think it is necessary.
